[workspace]
members = [
    "client",
    "files",
    "http",
    "http-codegen",
    "io",
    "server",
    "service",
    "test",
    "web",
    "examples",
    "http-encoding",
    "http-ws",
]

[patch.crates-io]
xitca-client = { path = "./client" }
xitca-files = { path = "./files" }
xitca-http = { path = "./http" }
xitca-http-codegen = { path = "./http-codegen" }
xitca-io = { path = "./io" }
xitca-server = { path = "./server" }
xitca-service = { path = "./service" }
xitca-web = { path = "./web" }
http-encoding = { path = "./http-encoding" }
http-ws = { path = "./http-ws" }

h3 = { git = "https://github.com/hyperium/h3.git" }
h3-quinn = { git = "https://github.com/hyperium/h3.git" }
tokio-uring = { git = "https://github.com/tokio-rs/tokio-uring.git" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
