[workspace]
members = [
    "actix-http-alt",
    "actix-server-alt",
    "actix-service-alt",
    "actix-web-alt",
    "examples"
]

[patch.crates-io]
actix-http-alt = { path = "./actix-http-alt" }
actix-server-alt = { path = "./actix-server-alt" }
actix-service-alt = { path = "./actix-service-alt" }
actix-web-alt = { path = "./actix-web-alt" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1