[workspace]
members = [
    "xitca-http",
    "xitca-server",
    "xitca-service",
    "xitca-web",
    "examples",
    "http-encoding",
    "http-ws",
]

[patch.crates-io]
xitca-http = { path = "./xitca-http" }
xitca-server = { path = "./xitca-server" }
xitca-service = { path = "./xitca-service" }
xitca-web = { path = "./xitca-web" }
http-encoding = { path = "./http-encoding" }
http-ws = { path = "./http-ws" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
