[package]
name = "examples"
version = "0.1.0"
edition = "2018"

[[example]]
name = "hello-world"
path = "hello-world.rs"

[[example]]
name = "unix"
path = "unix.rs"

[[example]]
name = "multi-services"
path = "multi-services.rs"

[[example]]
name = "websocket"
path = "websocket.rs"

[dependencies]
actix-http-alt = { version = "0.1", features = ["http2", "http3", "rustls", "openssl"] }
actix-server-alt = { version = "0.1", features = ["http3"] }
actix-service-alt = "0.1"
actix-web-alt = { version = "0.1", features = ["http2", "http3", "rustls", "openssl"] }
http-ws = "0.1"

bytes = "1"
env_logger = "0.8"
futures-util = "0.3"
http = "0.2"
log = "0.4"
rustls = "0.19"
tokio = { version = "1.5", features = ["macros", "rt"] }
openssl = "0.10"

h3-quinn = { git = "https://github.com/hyperium/h3.git" }
