[package]
name = "examples"
version = "0.1.0"
edition = "2018"

[[example]]
name = "hello-world"
path = "hello-world.rs"

[[example]]
name = "unix"
path = "unix.rs"

[[example]]
name = "multi-services"
path = "multi-services.rs"

[[example]]
name = "websocket"
path = "websocket.rs"

[[example]]
name = "io-uring"
path = "io-uring.rs"

[dependencies]
xitca-http = { version = "0.1", features = ["http2", "http3", "rustls", "openssl"] }
xitca-server= { version = "0.1", features = ["http3"] }
xitca-service = "0.1"
xitca-web = { version = "0.1", features = ["http2", "http3", "io-uring", "rustls", "openssl"] }
http-ws = "0.1"

bytes = "1"
futures-util = "0.3"
http = "0.2"
mimalloc = { version = "0.1.26", default-features = false }
rustls = "0.19"
tempfile = "3"
tokio = { version = "1.5", features = ["fs", "macros", "rt"] }
tokio-uring = "0.1"
tracing = "0.1.26"
tracing-subscriber = "0.2"
openssl = "0.10"

h3-quinn = { git = "https://github.com/hyperium/h3.git" }
