name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: add other os
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
    - uses: actions/checkout@master

    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        
    - run: rustup component add rustfmt
    - run: rustup component add clippy

    - name: check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all --bins --examples

    - name: check no-default-features
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --no-default-features

    - name: tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all
        
    - name: clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --tests --examples
    
    - name: fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
